Tarun, Gopi | BAH-1170 | MOBN-1628 | Add activeBlocks API parameter to surgicalBlocks get API call
openmrs/openmrs-module-operationtheater pull request #12
Opened 2021-04-06 05:10 UTC by tarunkumar-tw

…locks get call (#1)

* Tarun | MOBN-1628 | Add activeBlocks API parameter for surgical blocks API GET call

* Gopi,Tarun | MOBN-1628 | Updated Existing Unit Testcases to run as expected & Added Unit Testcases which will cover newly added code

* Gopi, Tarun | MOBN-1628 | Handle code review changes

Co-authored-by: gopikrishna-yaramothu <gopikrishna.y@thoughtworks.com>

2021-04-13 12:22 UTC, buvaneswari-arun approved these changes

2021-04-13 12:22 UTC, buvaneswari-arun commented
Kindly take care of the travis failure.

2021-04-14 05:30 UTC, binduak commented
> Kindly take care of the travis failure.

@buvaneswari-arun travis build was failing for previous commits too. I will check with @mks-d on this.

2021-04-14 05:36 UTC, buvaneswari-arun approved these changes

2021-04-14 08:21 UTC, mks-d requested changes
@tarunkumar-tw could you change [this](https://github.com/openmrs/openmrs-module-operationtheater/blob/1e6672bf8fae5e2dbeed8ea2b8ab5fcfd4b8a727/.travis.yml#L3) to `openjdk8` as part of this PR?

2021-04-14 09:55 UTC, mks-d approved these changes

2021-04-14 09:55 UTC, merged